image: docker:git

services:
  - name: docker:dind
    command: ["--experimental"]

variables:
  IMAGE: thecornershop/toolbox

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk add make

stages:
    - Build latest image

build:
  stage: Build latest image
  only:
    - master
  script:
    - make
