FROM registry.gitlab.com/thecornershop/toolbox:base

RUN pacman -Syy --noconfirm --noprogressbar && \
    su - user -c '\
      EDITOR=vim pacget --noconfirm --noedit gcc6 > /dev/null \
      ' && \
     pacman -Scc --noconfirm
