FROM registry.gitlab.com/thecornershop/toolbox:tools

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG DOCKER_USER_ID
ARG DOCKER_GROUP_ID

RUN [ $DOCKER_USER_ID == 0 ] || (groupmod -g $DOCKER_GROUP_ID user && \
    usermod -u $DOCKER_USER_ID user ) && \
    usermod -G tty,users,docker,git,sudo user && \
    chown -R user:user /home/user

USER user
ENV USER user
ENV HOME /home/user

WORKDIR /workdir

CMD ["/usr/bin/bash"]
